### ISSUE TITLE
Change server

### ISSUE THREAD

**Issue by gjimenezf** [AnalogMan151/FreeShopNX#11]
Now that it is not possible to download directly from the Nintendo servers, it should be useful to implement a setting to add a URL of your repository of games or add a torrent

**Comment by AnalogMan151** [comment]
FreeShopNX is not affected by recent CDN changes as long as your Switch is up to date. If you’re interested in another app capable of downloading and installing from a 3rd party server check out [DZ](https://github.com/blawar/nut/tree/master/dz)
