### ISSUE TITLE
can't download info.json, says waiting

### ISSUE THREAD

**Issue by sowarm** [AnalogMan151/FreeShopNX#2]

**Comment by AnalogMan151** [comment]
Try v0.3.0. Also, check that your config file is setup correctly.

**Comment by gordito1977** [comment]
Como se puede configurar el archivo. A mí tambien me pone que no tengo internet y estoy conectado.

**Comment by alfredogomez35** [comment]
Hey, sorry to bother you but I was wondering what url I should use for the title keys
