### ISSUE TITLE
Cert and tik install failed! 

### ISSUE THREAD

**Issue by DilandDuck101** [AnalogMan151/FreeShopNX#8]
I'm new to hacking in general. Can someone please help me and explain how to fix it? I can't find a result on Google. 
Thanks.

**Comment by AnalogMan151** [comment]
Be sure the required Ticket.tik file and Certificate.cert file are in the FreeShopNX folder. Also make sure you’re using a CFW with es signature patching like SXOS or ReiNX / Atmosphere with the appropriate patches.

**Comment by DilandDuck101** [comment]
I have ReiNX and the 2 files. Still doesn't work.

**Comment by AnalogMan151** [comment]
Does ReiNX have the FS.kip and ES title exeFS patch? These were removed from newer releases and so you much procure them yourself.

**Comment by DilandDuck101** [comment]
How can I know if I have the patch? Do you know where can I get them or do I have to look for them myself? Lastly, what do I do when I find them?

**Comment by MackyyTV** [comment]
if your using sxos make sure you have 1.4 and it will work fine but ReiNX I never had a problem with make sure you check your files

**Comment by DilandDuck101** [comment]
I found the "Darth Meteos' Super Special SD Stash v1.5" online and I downloaded it. What am I supposed to do with it now?

**Comment by DilandDuck101** [comment]
I got it working again! Someone sent me the official "Darth Meteos' Super Special SD Stash v1.5". I installed FreeshopNX and it worked! Thanks for the help.
